/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnaliticasRouteImport } from './routes/analiticas'
import { Route as CargarRouteImport } from './routes/cargar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliticasRoute = AnaliticasRouteImport.update({
  id: '/analiticas',
  path: '/analiticas',
  getParentRoute: () => rootRouteImport,
} as any)
const CargarRoute = CargarRouteImport.update({
  id: '/cargar',
  path: '/cargar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analiticas': typeof AnaliticasRoute
  '/cargar': typeof CargarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analiticas': typeof AnaliticasRoute
  '/cargar': typeof CargarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analiticas': typeof AnaliticasRoute
  '/cargar': typeof CargarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analiticas' | '/cargar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analiticas' | '/cargar'
  id: '__root__' | '/' | '/analiticas' | '/cargar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnaliticasRoute: typeof AnaliticasRoute
  CargarRoute: typeof CargarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analiticas': {
      id: '/analiticas'
      path: '/analiticas'
      fullPath: '/analiticas'
      preLoaderRoute: typeof AnaliticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargar': {
      id: '/cargar'
      path: '/cargar'
      fullPath: '/cargar'
      preLoaderRoute: typeof CargarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnaliticasRoute: AnaliticasRoute,
  CargarRoute: CargarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
